services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${VAULTWARDEN_DOMAIN}
      SIGNUPS_ALLOWED: ${VAULTWARDEN_SIGNUPS_ALLOWED}
    volumes:
      - /var/lib/vaultwarden/data:/data/
    networks:
      - public-gateway-network

networks:
  # docker network create public-gateway-network
  public-gateway-network:
    external: true
